services:
    ontime:
        container_name: ontime
        image: getontime/ontime:latest
        ports:
            - '4001:4001/tcp'
            - '8888:8888/udp'
            - '9999:9999/udp'
        volumes:
            - './ontime-data:/data/'
        environment:
            - TZ=Asia/Taipei
        restart: unless-stopped
    web:
        # build: .
        image: ghcr.io/simbafs/sitcon-production/web:main
        ports:
            - '80:80'
        depends_on:
            - ontime
        restart: unless-stopped
